### ISSUE TITLE
Use with Teensies?

### ISSUE THREAD

**Issue by tshort** [ahtn/tmk_keyboard#2]
Has anyone gotten this to work with two Teensies? Specifically, I'm trying to use the Teensy 2++. It's an at90usb1286, not an atmega32u4. I changed the makefile in this repo to the at90usb1286. As far as I can tell, one hand works, but the serial communication doesn't. (I haven't tried I2C.)

**Comment by ahtn** [comment]
Sorry for the late reply, but I think I know the reason why it's not working (at least one anyway). Had a quick look at the schematic of the Teensy2++, and it looks like the Teensy2++'s USB 5V supply is connected directly to VBUS pin on the mcu. The VBUS pin is what the code uses to check if the mcu is connected via USB or not, so both Teensy's will think they are connected via USB and will not send any data to each other. It works on the pro micro because the VCC pin has a diode/regulator between VCC and USB 5V, and so the VBUS pin doesn't see 5V when you connect the VCC pins together.

You could work around this by making one side always act as the master and the other always act as the slave.  Of course you will only be able to connect it to a computer only using one half then.  To do this  make `has_usb()` always return `true` for the master and `false` for the slave.  The qmk fork does it this way by default I think, so you could check that out as well:  https://github.com/qmk/qmk_firmware/tree/master/keyboards/lets_split

**Comment by tshort** [comment]
Wow. Awesome debugging, @ahtn! I'd have never figured that out. Adapting `has_usb` looks like a good option.

I switched to using two pro micros. QMK code [here](https://github.com/tshort/qmk_firmware/tree/master/keyboards/dactyl-manuform) and pics [here](http://imgur.com/a/v9eIO). Your code works great. I've already taken advantage of the feature where either side can be master. I needed it because the micro USB port broke off on one side. I could still use the keyboard by plugging the USB into the other side.

I may come back to trying the Teensy 2++ one day. I'd like to see if direct wiring all switches would be easier than messing with diodes.

I'll close this given that there's nothing really to do to support this.

**Comment by ahtn** [comment]
Wow, nice build! Glad you got it working
